// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Data;

#nullable disable

namespace TodoApp.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20260628215605_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TodoApp.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SortOrder = 1,
                            Status = "Creado",
                            Text = "Esta es una tarea de ejemplo creada automáticamente",
                            Title = "Tarea de ejemplo"
                        },
                        new
                        {
                            Id = 2,
                            SortOrder = 2,
                            Status = "EnEjecucion",
                            Text = "Leer la documentación del proyecto",
                            Title = "Revisar documentación"
                        },
                        new
                        {
                            Id = 3,
                            SortOrder = 3,
                            Status = "Terminado",
                            Text = "Instalar dependencias y configurar el entorno de desarrollo",
                            Title = "Configurar entorno"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
